name = "Ene4302a"
uuid = "b92ae0ef-2d67-44cc-8a56-2d81bbaef28c"
version = "1.0.0-DEV"
authors = ["Vincent Le Chenadec <vincentlechenadec@gmail.com> and contributors"]

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.41.5"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
